# Generated by Django 5.2 on 2025-04-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='negocios.atencion'),
        ),
    ]
